
MUSIC_PATH = "FOTO KITA BLUR - SAL PRIADI.mp3"
MUSIC_PATH_2 = "Hidup jokowi  sound meme.mp3"
BLUR_KERNEL_SIZE = 25
EDGE_CANNY_LOW = 50
EDGE_CANNY_HIGH = 150
FADE_DURATION = 0.4
MIN_DETECTION_CONFIDENCE = 0.3
MIN_TRACKING_CONFIDENCE = 0.3
FONT_SCALE_MAIN = 2.0
FONT_SCALE_STATUS = 0.6
TYPEWRITER_TEXT = "blurr"
TYPEWRITER_CHAR_DELAY = 0.12
TYPEWRITER_FADE_DURATION = 0.08
DEBOUNCE_FRAMES = 1
THUMB_THRESHOLD = 0.10
